### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by herohamp** [bjskistad/trapjs#2]
In 

var repeat = function(numTimes, {code}) {
    var Times = 0;
    do {
        code;
    } while (Times < numTimes);
};

the { and } are causing an issue. I suggest you remove them

**Comment by bjskistad** [comment]
The issue was already created by myself. :D I'm going to close this one and you can respond to mine with your suggestion. :P I do agree, they seem to be the problem, but there are no errors in the code. :/
