### ISSUE TITLE
Wiki

### ISSUE THREAD

**Issue by herohamp** [bjskistad/trapjs#4]
How can I edit the wiki?

**Comment by bjskistad** [comment]
I'll invite you to become a contributor. First, I would like to know, can I trust you?

**Comment by herohamp** [comment]
Never Mind I am create a whole new website will be live in 10-20mins and yes I am trust worthy!

**Comment by herohamp** [comment]
How you like? http://herohamp.github.io/TrapJSPage/

**Comment by bjskistad** [comment]
Love it!
